version: '3.9'

services:
  nuxt:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: dataverse_webapp
    environment:
      - DEBUG=1
    env_file:
      - .env
    volumes:
      - ./logs:/usr/src/nuxt-app/logs
    restart: unless-stopped
    expose:
      - 3000
    networks:
      - webapp
      - proxy

  nginx:
    image: nginx:alpine
    container_name: dataverse_webserver
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ${EB_LOG_BASE_DIR}/nginx:/var/log/nginx
    depends_on:
      - nuxt
    networks:
      - proxy

  # filebeat:
  #   image: docker.elastic.co/beats/filebeat:8.11.1
  #   container_name: dataverse_filebeat
  #   volumes:
  #     - /var/app/current/logs/:/logs:ro  # Mounts the log directory for Filebeat
  #     - ./filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
  #   environment:
  #     - cloud.id=trial1:YXAtc291dGgtMS5hd3MuZWxhc3RpYy1jbG91ZC5jb206NDQzJDE2MWMwZTc1YjMxNTRkYjRhNGUzNGNjNmQxNTk3NTEyJGM5NDlhN2ZjNDJkMDQzODdhZGUzM2M2OGViZjZiOTk5
  #     - cloud.auth=elastic:7q7bHnFXWD6M2kJVQgfSTbX2
  #   command: ["-e"]
  #   depends_on:
  #     - nuxt
  #   networks:
  #     - webapp
  #     - proxy

networks:
  webapp: ~
  proxy: ~