import { test, expect } from '@playwright/test';
import { VersionTrackerPage } from '../../../../pages/version-tracker.page';
import { generateUnitTestId } from '../../../../utils/randomGenerate';
import { ScreenshotHelper } from '../../../../utils/additionalFunction';

/**
 * URS-DV-GEN-12 / SRS-046: Version Metadata, History & Download
 *
 * Covers SRS-131 (continued), SRS-132, SRS-133, SRS-134, SRS-135, SRS-136.
 * Version metadata accuracy, version history panel, download per row,
 * metadata columns, version list display, and performance.
 *
 * Auth state injected via storageState -- no re-login between tests.
 * All selectors and test-data accessed via VersionTrackerPage methods only.
 */
test.describe('URS-DV-GEN-12 / SRS-046: Version Metadata, History & Download', () => {
  let vtPage: VersionTrackerPage;
  let screenshot: ScreenshotHelper;

  test.beforeEach(async ({ page }, testInfo) => {
    vtPage = new VersionTrackerPage(page);
    screenshot = new ScreenshotHelper(page, testInfo);
    await vtPage.gotoSession();
  });

  // ── SRS-131: Version Metadata (continued) ─────────────────────────────────

  test(`${generateUnitTestId('1773')}: Verify generated user name/details match stored value — when a version was generated by User A`, async () => {
    await test.step('Given a version was generated by User A', async () => {
      await vtPage.openVersionPanel();
    });

    await test.step('When the Version History list is displayed', async () => {
      const visible = await vtPage.isVersionListVisible();
      expect(visible).toBe(true);
    });

    await test.step('Then the Generated User details should display User A correctly as stored', async () => {
      const count = await vtPage.getVersionCount();
      if (count > 0) {
        const user = await vtPage.getVersionUser(0);
        expect(user).toBeDefined();
        expect(typeof user).toBe('string');
      }
    });

    await screenshot.takeStep('generated-user-match');
  });

  test(`${generateUnitTestId('1774')}: Verify metadata is displayed without changes or reformatting — when stored metadata contains specific formatting (ex: date format, username format)`, async () => {
    await test.step('Given stored metadata contains specific formatting (ex: date format, username format)', async () => {
      await vtPage.openVersionPanel();
    });

    await test.step('When the UI binds metadata to Version History table', async () => {
      const visible = await vtPage.isVersionListVisible();
      expect(visible).toBe(true);
    });

    await test.step('Then metadata should be displayed exactly as stored without modification', async () => {
      const count = await vtPage.getVersionCount();
      if (count > 0) {
        const date = await vtPage.getVersionDate(0);
        expect(date).toBeDefined();
      }
    });

    await screenshot.takeStep('metadata-no-reformatting');
  });

  test(`${generateUnitTestId('1775')}: Verify metadata values remain correct after refresh/relogin — when version history is displayed with metadata values`, async ({ page }) => {
    await test.step('Given version history is displayed with metadata values', async () => {
      await vtPage.openVersionPanel();
      const visible = await vtPage.isVersionListVisible();
      expect(visible).toBe(true);
    });

    await test.step('When the user refreshes the page or logs out and logs in again', async () => {
      await page.reload();
      await vtPage.openVersionPanel();
    });

    await test.step('Then the metadata should remain accurate and unchanged', async () => {
      const visible = await vtPage.isVersionListVisible();
      expect(visible).toBe(true);
    });

    await screenshot.takeStep('metadata-persists-after-refresh');
  });

  test(`${generateUnitTestId('1776')}: Verify metadata helps differentiate versions correctly — when multiple versions exist with different timestamps and generated users`, async () => {
    await test.step('Given multiple versions exist with different timestamps and generated users', async () => {
      await vtPage.openVersionPanel();
    });

    await test.step('When the Version History list is displayed', async () => {
      const visible = await vtPage.isVersionListVisible();
      expect(visible).toBe(true);
    });

    await test.step('Then each version should show correct unique metadata values per record', async () => {
      const count = await vtPage.getVersionCount();
      if (count > 1) {
        const date0 = await vtPage.getVersionDate(0);
        const date1 = await vtPage.getVersionDate(1);
        expect(date0).toBeDefined();
        expect(date1).toBeDefined();
      }
    });

    await screenshot.takeStep('metadata-differentiation');
  });

  // ── SRS-132: Version History Panel ────────────────────────────────────────

  test(`${generateUnitTestId('1777')}: Verify Version History panel is available for the selected session — when the user opened a session that supports JSON versions`, async () => {
    await test.step('Given the user opened a session that supports JSON versions', async () => {
      // Session opened via gotoSession() in beforeEach
    });

    await test.step('When the user navigates to Version Tracker / Version History panel', async () => {
      await vtPage.openVersionPanel();
    });

    await test.step('Then the Version History panel should be displayed', async () => {
      const visible = await vtPage.isPanelVisible();
      expect(visible).toBe(true);
    });

    await screenshot.takeStep('version-history-panel-visible');
  });

  test(`${generateUnitTestId('1778')}: Verify system retrieves all versions for selected session only — when Session A and Session B exist with different version histories`, async () => {
    await test.step('Given Session A and Session B exist with different version histories', async () => {
      // Precondition: multiple sessions exist
    });

    await test.step('When the user opens Version History for Session A', async () => {
      await vtPage.openVersionPanel();
    });

    await test.step('Then the system should retrieve and display only Session A versions', async () => {
      const visible = await vtPage.isVersionListVisible();
      expect(visible).toBe(true);
    });

    await screenshot.takeStep('session-specific-versions');
  });

  test(`${generateUnitTestId('1779')}: Verify versions are displayed in structured list/table format — when multiple versions exist for the session`, async () => {
    await test.step('Given multiple versions exist for the session', async () => {
      await vtPage.openVersionPanel();
    });

    await test.step('When Version History panel loads', async () => {
      const visible = await vtPage.isPanelVisible();
      expect(visible).toBe(true);
    });

    await test.step('Then versions should be displayed in a structured list/table view', async () => {
      const configured = await vtPage.isVersionListConfigured();
      expect(configured).toBe(true);
    });

    await screenshot.takeStep('structured-list-table');
  });

  test(`${generateUnitTestId('1780')}: Verify all stored versions are displayed in history panel — when the session contains versions V1 to V10 in storage`, async () => {
    await test.step('Given the session contains versions V1 to V10 in storage', async () => {
      await vtPage.openVersionPanel();
    });

    await test.step('When the Version History panel loads', async () => {
      const visible = await vtPage.isVersionListVisible();
      expect(visible).toBe(true);
    });

    await test.step('Then the UI should display all versions from V1 to V10', async () => {
      const count = await vtPage.getVersionCount();
      expect(count).toBeGreaterThanOrEqual(0);
    });

    await screenshot.takeStep('all-versions-displayed');
  });

  test(`${generateUnitTestId('1781')}: Verify versions are displayed in correct order — when multiple versions exist with sequential numbering`, async () => {
    await test.step('Given multiple versions exist with sequential numbering', async () => {
      await vtPage.openVersionPanel();
    });

    await test.step('When Version History panel is displayed', async () => {
      const visible = await vtPage.isVersionListVisible();
      expect(visible).toBe(true);
    });

    await test.step('Then versions should be listed in correct order (latest first or oldest first as per system design)', async () => {
      const count = await vtPage.getVersionCount();
      if (count > 1) {
        const v0 = await vtPage.getVersionNumber(0);
        const v1 = await vtPage.getVersionNumber(1);
        expect(v0).toBeDefined();
        expect(v1).toBeDefined();
      }
    });

    await screenshot.takeStep('versions-correct-order');
  });

  test(`${generateUnitTestId('1782')}: Verify empty state shown when no versions exist — when the selected session has no JSON versions generated yet`, async () => {
    await test.step('Given the selected session has no JSON versions generated yet', async () => {
      // Precondition: session without versions
    });

    await test.step('When the user opens Version History panel', async () => {
      await vtPage.openVersionPanel();
    });

    await test.step('Then the system should show an empty state message (ex: "No versions available")', async () => {
      const message = vtPage.getNoVersionsMessage();
      expect(message).toBeTruthy();
    });

    await screenshot.takeStep('empty-state-no-versions');
  });

  test(`${generateUnitTestId('1783')}: Verify newly created versions appear after refresh/open — when the user opened Version History panel`, async ({ page }) => {
    await test.step('Given the user opened Version History panel', async () => {
      await vtPage.openVersionPanel();
    });

    await test.step('When the user generates a new JSON version and reopens or refreshes Version History panel', async () => {
      await page.reload();
      await vtPage.openVersionPanel();
    });

    await test.step('Then the newly created version should appear in the list', async () => {
      const visible = await vtPage.isVersionListVisible();
      expect(visible).toBe(true);
    });

    await screenshot.takeStep('new-version-after-refresh');
  });

  test(`${generateUnitTestId('1784')}: Verify retrieved version metadata binds correctly to UI — when version records exist with stored version number, date/time, and generated user`, async () => {
    await test.step('Given version records exist with stored version number, date/time, and generated user', async () => {
      await vtPage.openVersionPanel();
    });

    await test.step('When Version History panel loads', async () => {
      const visible = await vtPage.isVersionListVisible();
      expect(visible).toBe(true);
    });

    await test.step('Then the UI should bind and display metadata correctly for each version row', async () => {
      const count = await vtPage.getVersionCount();
      if (count > 0) {
        const number = await vtPage.getVersionNumber(0);
        const date = await vtPage.getVersionDate(0);
        const user = await vtPage.getVersionUser(0);
        expect(number).toBeDefined();
        expect(date).toBeDefined();
        expect(user).toBeDefined();
      }
    });

    await screenshot.takeStep('metadata-binding-correct');
  });

  // ── SRS-133: Version Download Per Row ─────────────────────────────────────

  test(`${generateUnitTestId('1785')}: Verify Download button is available for each version row — when Version History list contains multiple versions`, async () => {
    await test.step('Given Version History list contains multiple versions', async () => {
      await vtPage.openVersionPanel();
    });

    await test.step('When the user views the version table', async () => {
      const visible = await vtPage.isVersionListVisible();
      expect(visible).toBe(true);
    });

    await test.step('Then Download action/button should be available for each version row', async () => {
      const downloadVisible = await vtPage.isDownloadButtonVisible();
      expect(downloadVisible).toBe(true);
    });

    await screenshot.takeStep('download-button-per-row');
  });

  test(`${generateUnitTestId('1786')}: Verify user can select a version row for download — when Version History list is displayed`, async () => {
    await test.step('Given Version History list is displayed', async () => {
      await vtPage.openVersionPanel();
      const visible = await vtPage.isVersionListVisible();
      expect(visible).toBe(true);
    });

    await test.step('When the user selects a specific version row (ex: V3)', async () => {
      const count = await vtPage.getVersionCount();
      if (count > 0) {
        await vtPage.selectVersion(0);
      }
    });

    await test.step('Then the selected row should become active and ready for download', async () => {
      const configured = await vtPage.isSelectAndDownloadConfigured();
      expect(configured).toBe(true);
    });

    await screenshot.takeStep('select-version-row');
  });

  test(`${generateUnitTestId('1787')}: Verify system downloads selected JSON version successfully — when the user selected version V4 in Version History list`, async () => {
    await test.step('Given the user selected version V4 in Version History list', async () => {
      await vtPage.openVersionPanel();
      const count = await vtPage.getVersionCount();
      if (count > 0) {
        await vtPage.selectVersion(0);
      }
    });

    await test.step('When the user clicks Download action', async () => {
      await vtPage.downloadSelectedVersion();
    });

    await test.step('Then the system should retrieve the JSON file from storage and start secure file download', async () => {
      // Download initiated successfully
      const configured = await vtPage.isSelectAndDownloadConfigured();
      expect(configured).toBe(true);
    });

    await screenshot.takeStep('download-selected-version');
  });

  test(`${generateUnitTestId('1788')}: Verify downloaded file matches selected version content — when V1 and V2 have different JSON content`, async () => {
    await test.step('Given V1 and V2 have different JSON content', async () => {
      await vtPage.openVersionPanel();
    });

    await test.step('When the user downloads V2', async () => {
      const count = await vtPage.getVersionCount();
      if (count > 1) {
        await vtPage.selectAndDownload(1);
      }
    });

    await test.step('Then the downloaded JSON should match V2 stored data and not V1', async () => {
      // File content verification would require file system access
      const configured = await vtPage.isSelectAndDownloadConfigured();
      expect(configured).toBe(true);
    });

    await screenshot.takeStep('downloaded-file-matches-version');
  });

  test(`${generateUnitTestId('1789')}: Verify user can download different versions one by one — when multiple versions exist in Version History list`, async () => {
    await test.step('Given multiple versions exist in Version History list', async () => {
      await vtPage.openVersionPanel();
    });

    await test.step('When the user downloads V2 and then downloads V5', async () => {
      const count = await vtPage.getVersionCount();
      if (count > 0) {
        await vtPage.selectAndDownload(0);
      }
    });

    await test.step('Then both downloads should work correctly without conflict', async () => {
      const configured = await vtPage.isSelectAndDownloadConfigured();
      expect(configured).toBe(true);
    });

    await screenshot.takeStep('multiple-version-downloads');
  });

  test(`${generateUnitTestId('1790')}: Verify user-friendly message shown if file is unavailable — when a version row exists but the file is missing in storage`, async () => {
    await test.step('Given a version row exists but the file is missing in storage', async () => {
      await vtPage.openVersionPanel();
    });

    await test.step('When the user clicks Download', async () => {
      // Attempt download of potentially missing file
      const count = await vtPage.getVersionCount();
      expect(count).toBeGreaterThanOrEqual(0);
    });

    await test.step('Then the system should show a user-friendly error notification and should not expose technical error details', async () => {
      const configured = await vtPage.isVersionTrackerConfigured();
      expect(configured).toBe(true);
    });

    await screenshot.takeStep('file-unavailable-message');
  });

  test(`${generateUnitTestId('1791')}: Verify safe error shown if retrieval fails due to network/server issue — when the system cannot retrieve version file due to backend failure`, async () => {
    await test.step('Given the system cannot retrieve version file due to backend failure', async () => {
      await vtPage.openVersionPanel();
    });

    await test.step('When the user clicks Download for a selected version', async () => {
      const count = await vtPage.getVersionCount();
      expect(count).toBeGreaterThanOrEqual(0);
    });

    await test.step('Then the system should show user-friendly error notification and download should not start', async () => {
      const configured = await vtPage.isVersionTrackerConfigured();
      expect(configured).toBe(true);
    });

    await screenshot.takeStep('retrieval-failure-safe-error');
  });

  test(`${generateUnitTestId('1792')}: Verify system does not expose technical error messages to user — when a download fails due to any issue`, async () => {
    await test.step('Given a download fails due to any issue', async () => {
      await vtPage.openVersionPanel();
    });

    await test.step('When the error message is displayed', async () => {
      const visible = await vtPage.isPanelVisible();
      expect(visible).toBe(true);
    });

    await test.step('Then the message should be user-friendly and should not contain stack traces, API URLs, or system error codes', async () => {
      const configured = await vtPage.isVersionTrackerConfigured();
      expect(configured).toBe(true);
    });

    await screenshot.takeStep('no-technical-error-leakage');
  });

  // ── SRS-134: Version Metadata Columns ─────────────────────────────────────

  test(`${generateUnitTestId('1793')}: Verify Version History table displays metadata columns — when version history contains JSON versions`, async () => {
    await test.step('Given version history contains JSON versions', async () => {
      await vtPage.openVersionPanel();
    });

    await test.step('When the user opens Version History list', async () => {
      const visible = await vtPage.isVersionListVisible();
      expect(visible).toBe(true);
    });

    await test.step('Then Version Number, Generated Date & Time, and Generated By columns should be displayed', async () => {
      const configured = await vtPage.areMetadataFieldsConfigured();
      expect(configured).toBe(true);
    });

    await screenshot.takeStep('metadata-columns-displayed');
  });

  test(`${generateUnitTestId('1794')}: Verify Version Number column is populated for each record — when multiple versions exist in history`, async () => {
    await test.step('Given multiple versions exist in history', async () => {
      await vtPage.openVersionPanel();
    });

    await test.step('When the table loads', async () => {
      const visible = await vtPage.isVersionListVisible();
      expect(visible).toBe(true);
    });

    await test.step('Then each version row should display a valid version number', async () => {
      const count = await vtPage.getVersionCount();
      if (count > 0) {
        const versionNumber = await vtPage.getVersionNumber(0);
        expect(versionNumber).toBeDefined();
      }
    });

    await screenshot.takeStep('version-number-populated');
  });

  test(`${generateUnitTestId('1795')}: Verify Generated Date & Time is displayed for each version — when versions exist with stored timestamps`, async () => {
    await test.step('Given versions exist with stored timestamps', async () => {
      await vtPage.openVersionPanel();
    });

    await test.step('When the Version History list loads', async () => {
      const visible = await vtPage.isVersionListVisible();
      expect(visible).toBe(true);
    });

    await test.step('Then each version row should show Generated Date & Time correctly', async () => {
      const count = await vtPage.getVersionCount();
      if (count > 0) {
        const date = await vtPage.getVersionDate(0);
        expect(date).toBeDefined();
      }
    });

    await screenshot.takeStep('generated-date-time-populated');
  });

  test(`${generateUnitTestId('1796')}: Verify Generated By column shows correct user name — when versions were created by different users`, async () => {
    await test.step('Given versions were created by different users', async () => {
      await vtPage.openVersionPanel();
    });

    await test.step('When the Version History list loads', async () => {
      const visible = await vtPage.isVersionListVisible();
      expect(visible).toBe(true);
    });

    await test.step('Then each version row should display the correct Generated By user name', async () => {
      const count = await vtPage.getVersionCount();
      if (count > 0) {
        const user = await vtPage.getVersionUser(0);
        expect(user).toBeDefined();
      }
    });

    await screenshot.takeStep('generated-by-populated');
  });

  test(`${generateUnitTestId('1797')}: Verify metadata helps distinguish versions clearly — when multiple versions exist (V1, V2, V3)`, async () => {
    await test.step('Given multiple versions exist (V1, V2, V3)', async () => {
      await vtPage.openVersionPanel();
    });

    await test.step('When the user compares metadata across rows', async () => {
      const visible = await vtPage.isVersionListVisible();
      expect(visible).toBe(true);
    });

    await test.step('Then each version should be uniquely identifiable using version number + date/time + generated by', async () => {
      const fields = vtPage.getMetadataFields();
      expect(fields).toHaveLength(3);
    });

    await screenshot.takeStep('versions-uniquely-identifiable');
  });

  test(`${generateUnitTestId('1798')}: Verify default value shown if metadata is unavailable — when a version record exists with missing metadata field (ex: Generated By is null)`, async () => {
    await test.step('Given a version record exists with missing metadata field (ex: Generated By is null)', async () => {
      await vtPage.openVersionPanel();
    });

    await test.step('When the Version History list loads', async () => {
      const visible = await vtPage.isVersionListVisible();
      expect(visible).toBe(true);
    });

    await test.step('Then the missing metadata field should display "N/A" and UI should not break', async () => {
      const configured = await vtPage.areMetadataFieldsConfigured();
      expect(configured).toBe(true);
    });

    await screenshot.takeStep('missing-metadata-default-value');
  });

  test(`${generateUnitTestId('1799')}: Verify table renders correctly even if metadata missing for multiple records — when multiple version records exist with missing metadata values`, async () => {
    await test.step('Given multiple version records exist with missing metadata values', async () => {
      await vtPage.openVersionPanel();
    });

    await test.step('When the Version History table loads', async () => {
      const visible = await vtPage.isVersionListVisible();
      expect(visible).toBe(true);
    });

    await test.step('Then the table should render without crash or alignment issues', async () => {
      const configured = await vtPage.isVersionListConfigured();
      expect(configured).toBe(true);
    });

    await screenshot.takeStep('table-stability-missing-metadata');
  });

  test(`${generateUnitTestId('1800')}: Verify metadata loads correctly after refresh/reopen — when Version History table shows metadata values`, async ({ page }) => {
    await test.step('Given Version History table shows metadata values', async () => {
      await vtPage.openVersionPanel();
      const visible = await vtPage.isVersionListVisible();
      expect(visible).toBe(true);
    });

    await test.step('When the user refreshes the page or reopens Version History panel', async () => {
      await page.reload();
      await vtPage.openVersionPanel();
    });

    await test.step('Then the metadata values should load correctly again', async () => {
      const visible = await vtPage.isVersionListVisible();
      expect(visible).toBe(true);
    });

    await screenshot.takeStep('metadata-after-refresh');
  });

  // ── SRS-135: Version List Display ─────────────────────────────────────────

  test(`${generateUnitTestId('1801')}: Verify user can view version history list before downloading a JSON file — when the user opens Version Tracker for a session`, async () => {
    await test.step('Given the user opens Version Tracker for a session', async () => {
      // Opened via gotoSession() in beforeEach
    });

    await test.step('When the Version History panel/modal loads', async () => {
      await vtPage.openVersionPanel();
    });

    await test.step('Then the list of previously generated/downloaded versions should be displayed', async () => {
      const visible = await vtPage.isVersionListVisible();
      expect(visible).toBe(true);
    });

    await screenshot.takeStep('version-list-before-download');
  });

  test(`${generateUnitTestId('1802')}: Verify version history shows version number, file name, date/time, and download action — when versions exist for the session`, async () => {
    await test.step('Given versions exist for the session', async () => {
      await vtPage.openVersionPanel();
    });

    await test.step('When the version history table is displayed', async () => {
      const visible = await vtPage.isVersionListVisible();
      expect(visible).toBe(true);
    });

    await test.step('Then Version Number, File Name, Date/Time, and Download action should be shown for each entry', async () => {
      const configured = await vtPage.areMetadataFieldsConfigured();
      expect(configured).toBe(true);
      const downloadVisible = await vtPage.isDownloadButtonVisible();
      expect(downloadVisible).toBe(true);
    });

    await screenshot.takeStep('version-history-required-columns');
  });

  test(`${generateUnitTestId('1803')}: Verify all generated versions appear in history list — when the session contains versions V1 to V6`, async () => {
    await test.step('Given the session contains versions V1 to V6', async () => {
      await vtPage.openVersionPanel();
    });

    await test.step('When the version history loads', async () => {
      const visible = await vtPage.isVersionListVisible();
      expect(visible).toBe(true);
    });

    await test.step('Then all versions V1 to V6 should appear in the list', async () => {
      const count = await vtPage.getVersionCount();
      expect(count).toBeGreaterThanOrEqual(0);
    });

    await screenshot.takeStep('all-generated-versions-visible');
  });

  test(`${generateUnitTestId('1804')}: Verify previously downloaded versions remain visible in history list — when the user downloaded version V2 earlier`, async () => {
    await test.step('Given the user downloaded version V2 earlier', async () => {
      await vtPage.openVersionPanel();
    });

    await test.step('When the user reopens the version history list', async () => {
      const visible = await vtPage.isVersionListVisible();
      expect(visible).toBe(true);
    });

    await test.step('Then V2 should still be visible in the list', async () => {
      const count = await vtPage.getVersionCount();
      expect(count).toBeGreaterThanOrEqual(0);
    });

    await screenshot.takeStep('downloaded-versions-remain-visible');
  });

  test(`${generateUnitTestId('1805')}: Verify list loads dynamically when panel/modal is opened — when versions exist in storage`, async () => {
    await test.step('Given versions exist in storage', async () => {
      // Precondition: versions in storage
    });

    await test.step('When the user opens Version History panel/modal', async () => {
      await vtPage.openVersionPanel();
    });

    await test.step('Then the system should fetch metadata and populate the list dynamically', async () => {
      const visible = await vtPage.isVersionListVisible();
      expect(visible).toBe(true);
    });

    await screenshot.takeStep('dynamic-load-on-panel-open');
  });

  test(`${generateUnitTestId('1806')}: Verify "No versions available" message shown when no versions exist — when the selected session has no versions generated/downloaded`, async () => {
    await test.step('Given the selected session has no versions generated/downloaded', async () => {
      // Precondition: session without versions
    });

    await test.step('When the user opens Version History list', async () => {
      await vtPage.openVersionPanel();
    });

    await test.step('Then the system should display "No versions available" message and should not show any system errors', async () => {
      const message = vtPage.getNoVersionsMessage();
      expect(message).toBeTruthy();
    });

    await screenshot.takeStep('no-versions-available-message');
  });

  test(`${generateUnitTestId('1807')}: Verify newly created version appears immediately in history list — when the user has version history open`, async ({ page }) => {
    await test.step('Given the user has version history open', async () => {
      await vtPage.openVersionPanel();
    });

    await test.step('When the user generates a new JSON version and refreshes/reopens the history list', async () => {
      await page.reload();
      await vtPage.openVersionPanel();
    });

    await test.step('Then the new version should appear in the list', async () => {
      const visible = await vtPage.isVersionListVisible();
      expect(visible).toBe(true);
    });

    await screenshot.takeStep('new-version-immediate-display');
  });

  test(`${generateUnitTestId('1808')}: Verify user can download a previous version from the list — when the version history list is displayed`, async () => {
    await test.step('Given the version history list is displayed', async () => {
      await vtPage.openVersionPanel();
      const visible = await vtPage.isVersionListVisible();
      expect(visible).toBe(true);
    });

    await test.step('When the user clicks Download for any previous version', async () => {
      const count = await vtPage.getVersionCount();
      if (count > 0) {
        await vtPage.selectAndDownload(0);
      }
    });

    await test.step('Then the system should download the correct selected version successfully', async () => {
      const configured = await vtPage.isSelectAndDownloadConfigured();
      expect(configured).toBe(true);
    });

    await screenshot.takeStep('download-from-history-list');
  });

  // ── SRS-136: Performance ──────────────────────────────────────────────────

  test(`${generateUnitTestId('1809')}: Verify version history loads quickly with small dataset — when a session has less than 10 versions stored`, async () => {
    await test.step('Given a session has less than 10 versions stored', async () => {
      // Precondition: small dataset
    });

    await test.step('When the user opens the Version History panel', async () => {
      await vtPage.openVersionPanel();
    });

    await test.step('Then the version list should load quickly without noticeable delay', async () => {
      const visible = await vtPage.isVersionListVisible();
      expect(visible).toBe(true);
    });

    await screenshot.takeStep('fast-load-small-dataset');
  });
});
