import { test, expect } from '@playwright/test';
import { VersionTrackerPage } from '../../pages/version-tracker.page';
import { generateUnitTestId } from '../../utils/randomGenerate';
import { ScreenshotHelper } from '../../utils/additionalFunction';

/**
 * URS-DV-DM-17: Version Tracker – JSON Download Versions
 *
 * Auth state injected via storageState — no re-login between tests.
 * All selectors and test-data accessed via VersionTrackerPage methods only.
 */
test.describe('URS-DV-DM-17: Version Tracker – JSON Download Versions', () => {
  let vtPage: VersionTrackerPage;
  let screenshot: ScreenshotHelper;

  test.beforeEach(async ({ page }, testInfo) => {
    vtPage = new VersionTrackerPage(page);
    screenshot = new ScreenshotHelper(page, testInfo);
    await vtPage.gotoSession();
  });

  // ── SRS-126: Sequential Version Numbering ────────────────────────────────

  test(`${generateUnitTestId('126')}: Verify version number selector is configured for sequential numbering`, async () => {
    const configured = await vtPage.isVersionTrackerConfigured();
    expect(configured).toBe(true);
    await screenshot.takeStep('sequential-versioning');
  });

  // ── SRS-127: Immutable Version Storage ───────────────────────────────────

  test(`${generateUnitTestId('127')}: Verify immutable flag is set to true in version tracker data`, async () => {
    const isImmutable = await vtPage.isImmutableFlagSet();
    expect(isImmutable).toBe(true);
    await screenshot.takeStep('immutable-storage');
  });

  // ── SRS-128: Secure JSON Version Download ────────────────────────────────

  test(`${generateUnitTestId('128')}: Verify download button selector is configured for secure download`, async () => {
    const configured = await vtPage.isVersionTrackerConfigured();
    expect(configured).toBe(true);
    await screenshot.takeStep('secure-download');
  });

  // ── SRS-129: Mandatory Version Selection Before Download ──────────────────

  test(`${generateUnitTestId('129')}: Verify select-and-download flow selectors are configured`, async () => {
    const configured = await vtPage.isSelectAndDownloadConfigured();
    expect(configured).toBe(true);
    await screenshot.takeStep('mandatory-selection');
  });

  // ── SRS-130: Single Version Selection Control ─────────────────────────────

  test(`${generateUnitTestId('130')}: Verify version select radio selector is configured for single selection`, async () => {
    const configured = await vtPage.isSelectAndDownloadConfigured();
    expect(configured).toBe(true);
    await screenshot.takeStep('single-selection');
  });

  // ── SRS-131: Accurate Metadata Display ───────────────────────────────────

  test(`${generateUnitTestId('131')}: Verify version metadata fields (Version, Created At, Generated By) are configured`, async () => {
    const configured = await vtPage.areMetadataFieldsConfigured();
    expect(configured).toBe(true);
    const fields = vtPage.getMetadataFields();
    expect(fields).toContain('Version');
    expect(fields).toContain('Created At');
    expect(fields).toContain('Generated By');
    await screenshot.takeStep('metadata-display');
  });

  // ── SRS-132: Load Version History ────────────────────────────────────────

  test(`${generateUnitTestId('132')}: Verify version list selector is configured for history loading`, async () => {
    const configured = await vtPage.isVersionListConfigured();
    expect(configured).toBe(true);
    await screenshot.takeStep('load-history');
  });

  // ── SRS-133: Select and Download Specific Version ────────────────────────

  test(`${generateUnitTestId('133')}: Verify version select radio and download button selectors are paired`, async () => {
    const configured = await vtPage.isSelectAndDownloadConfigured();
    expect(configured).toBe(true);
    await screenshot.takeStep('select-download');
  });

  // ── SRS-134: Version Metadata Visibility ─────────────────────────────────

  test(`${generateUnitTestId('134')}: Verify version date and user selectors are configured for metadata visibility`, async () => {
    const configured = await vtPage.isVersionListConfigured();
    expect(configured).toBe(true);
    await screenshot.takeStep('metadata-visibility');
  });

  // ── SRS-135: View Previous JSON Versions ─────────────────────────────────

  test(`${generateUnitTestId('135')}: Verify version tracker panel selector is configured for history view`, async () => {
    const configured = await vtPage.isVersionTrackerConfigured();
    expect(configured).toBe(true);
    await screenshot.takeStep('view-versions');
  });

  // ── SRS-136: Version History Retrieval Performance ────────────────────────

  test(`${generateUnitTestId('136')}: Verify version tracker button is configured for fast panel retrieval`, async () => {
    const configured = await vtPage.isVersionTrackerConfigured();
    expect(configured).toBe(true);
    await screenshot.takeStep('retrieval-performance');
  });

  // ── SRS-137: Version Download Reliability ─────────────────────────────────

  test(`${generateUnitTestId('137')}: Verify download button is configured for reliable version download`, async () => {
    const configured = await vtPage.isVersionTrackerConfigured();
    expect(configured).toBe(true);
    await screenshot.takeStep('download-reliability');
  });

  // ── SRS-138: Version Data Security ────────────────────────────────────────

  test(`${generateUnitTestId('138')}: Verify no-versions message is configured for secure empty state`, async () => {
    const message = vtPage.getNoVersionsMessage();
    expect(message).toBeTruthy();
    await screenshot.takeStep('data-security');
  });

  // ── SRS-139: Version History Usability ────────────────────────────────────

  test(`${generateUnitTestId('139')}: Verify full version tracker selector suite is configured for usability`, async () => {
    const configured = await vtPage.isVersionTrackerConfigured();
    expect(configured).toBe(true);
    await screenshot.takeStep('usability');
  });

  // ── SRS-140: Version History Scalability ──────────────────────────────────

  test(`${generateUnitTestId('140')}: Verify version item template supports scalable history lists`, async () => {
    const configured = await vtPage.isVersionListConfigured();
    expect(configured).toBe(true);
    await screenshot.takeStep('scalability');
  });
});
