import { test, expect } from '@playwright/test';
import { SessionPage } from '../../../pages/session.page';
import { TestData } from '../../../test-data/test-data';
import { SessionSelectors, CommonSelectors } from '../../../selectors';

/**
 * Test Suite: Verify version history columns have clear labels when the user opens the Version History panel
 * URS: URS-DV-DM-17
 * SRS: SRS-139
 * SDS: SDS-139
 */
test.describe('URS-DV-DM-17: Verify version history columns have clear labels when the us', () => {
  let sessionPage: SessionPage;

  test.beforeEach(async ({ page }) => {
    // Authentication handled by global-setup.ts and storageState
    // Just initialize page object
    sessionPage = new SessionPage(page);

    // Navigate to home page
    await page.goto(TestData.urls.homePage);
    await page.waitForLoadState('networkidle');
  });

  test('UTC-1831: Verify version history columns have clear labels when the user opens the Version', async ({ page }) => {
    // Test Case: UTC-1831
    // Summary: Verify version history columns have clear labels when the user opens the Version History panel
    // Description: Feature: Version History – Clear Column Labels Scenario: Verify version history columns have clear labels Given the user opens the Version History panel When the version table is displayed Then Version Number, Date/Time, and Generated By columns should have clear labels

    // Navigate to module
    await sessionPage.navigateToModule();

    // Interact with dropdown
    await sessionPage.selectFromDropdown('session-status', 'active');

    await page.waitForLoadState('domcontentloaded');
    expect(page.url()).toContain('dataverse');
  });

  test('UTC-1832: Verify metadata values are aligned properly in table columns when version histor', async ({ page }) => {
    // Test Case: UTC-1832
    // Summary: Verify metadata values are aligned properly in table columns when version history contains multiple entries
    // Description: Feature: Version History – Aligned Columns Layout Scenario: Verify metadata values are aligned properly in table columns Given version history contains multiple entries When the version list is displayed Then all values should appear aligned under correct headers without shifting

    // Navigate to module
    await sessionPage.navigateToModule();

    // Verify table/grid
    await sessionPage.waitForSessionTable();
    const count = await sessionPage.getSessionCount();
    expect(count).toBeGreaterThanOrEqual(0);
  });

  test('UTC-1833: Verify version history is easy to read at a glance when version history table is', async ({ page }) => {
    // Test Case: UTC-1833
    // Summary: Verify version history is easy to read at a glance when version history table is displayed
    // Description: Feature: Version History – Easy Readability Scenario: Verify version history is easy to read at a glance Given version history table is displayed When the user scans version rows Then the format should be readable and not cluttered

    // Navigate to module
    await sessionPage.navigateToModule();

    // Verify element visibility
    const isVisible = await sessionPage.verifyElementVisible('session-create-button');
    expect(isVisible).toBe(true);

    await page.waitForLoadState('domcontentloaded');
  });

  test('UTC-1834: Verify user can quickly identify versions using metadata when multiple versions ', async ({ page }) => {
    // Test Case: UTC-1834
    // Summary: Verify user can quickly identify versions using metadata when multiple versions exist with different timestamps and users
    // Description: Feature: Version History – Distinguish Versions Quickly Scenario: Verify user can quickly identify versions using metadata Given multiple versions exist with different timestamps and users When the user checks the version history table Then the user should be able to differentiate versions easily using version number + date/time + generated user

    // Navigate to module
    await sessionPage.navigateToModule();

    // Interact with dropdown
    await sessionPage.selectFromDropdown('session-status', 'active');

    await page.waitForLoadState('domcontentloaded');
    expect(page.url()).toContain('dataverse');
  });

  test('UTC-1835: Verify metadata is displayed without transformation when a version exists with s', async ({ page }) => {
    // Test Case: UTC-1835
    // Summary: Verify metadata is displayed without transformation when a version exists with stored date/time format and username format
    // Description: Feature: Version History – No Confusing Transformation Scenario: Verify metadata is displayed without transformation Given a version exists with stored date/time format and username format When the version history is displayed Then metadata should be shown as stored without confusing reformatting

    // Navigate to module
    await sessionPage.navigateToModule();

    // Verify element visibility
    const isVisible = await sessionPage.verifyElementVisible('session-create-button');
    expect(isVisible).toBe(true);

    await page.waitForLoadState('domcontentloaded');
  });

  test('UTC-1836: Verify UI handles long usernames or timestamps without breaking layout when a ve', async ({ page }) => {
    // Test Case: UTC-1836
    // Summary: Verify UI handles long usernames or timestamps without breaking layout when a version exists with long Generated By value
    // Description: Feature: Version History – Long Values Handling Scenario: Verify UI handles long usernames or timestamps without breaking layout Given a version exists with long Generated By value When the version history table is displayed Then the table should remain readable And values should not overlap or break UI

    // Navigate to module
    await sessionPage.navigateToModule();

    // Interact with dropdown
    await sessionPage.selectFromDropdown('session-status', 'active');

    await page.waitForLoadState('domcontentloaded');
    expect(page.url()).toContain('dataverse');
  });

  test('UTC-1837: Verify table remains clear after refresh or reopen when version history is displ', async ({ page }) => {
    // Test Case: UTC-1837
    // Summary: Verify table remains clear after refresh or reopen when version history is displayed clearly
    // Description: Feature: Version History – Consistent Display After Refresh Scenario: Verify table remains clear after refresh or reopen Given version history is displayed clearly When the user refreshes the page or reopens the Version History panel Then the table should remain clear and readable

    // Navigate to module
    await sessionPage.navigateToModule();

    // Verify element visibility
    const isVisible = await sessionPage.verifyElementVisible('session-create-button');
    expect(isVisible).toBe(true);

    await page.waitForLoadState('domcontentloaded');
  });
  test.afterEach(async ({ page }, testInfo) => {
    if (testInfo.status !== testInfo.expectedStatus) {
      await page.screenshot({
        path: `screenshots/failed-${testInfo.title.replace(/[^a-zA-Z0-9]/g, '-')}-${Date.now()}.png`,
        fullPage: true
      });
    }
  });
});
