import { test, expect } from '../../../fixtures/auth.fixture';
import { SessionPage } from '../../../pages/session.page';
import { TestData } from '../../../test-data/test-data';
import { SessionSelectors, CommonSelectors } from '../../../selectors';

/**
 * Test Suite: Verify Version History table displays metadata columns when version history contains JSON versions
 * URS: URS-DV-DM-17
 * SRS: SRS-134
 * SDS: SDS-134
 */
test.describe('URS-DV-DM-17: Verify Version History table displays metadata columns when ', () => {
  let sessionPage: SessionPage;

  test.beforeEach(async ({ page }) => {
    // Authentication handled by global-setup.ts and storageState
    // Just initialize page object
    sessionPage = new SessionPage(page);

    // Navigate to home page
    await page.goto(TestData.urls.homePage);
    await page.waitForLoadState('load');
  });

  test('UTC-1793: Verify Version History table displays metadata columns when version history cont', async ({ page }) => {
    // Test Case: UTC-1793
    // Summary: Verify Version History table displays metadata columns when version history contains JSON versions
    // Description: Feature: Version Metadata – Metadata Columns Displayed Scenario: Verify Version History table displays metadata columns Given version history contains JSON versions When the user opens Version History list Then Version Number, Generated Date & Time, and Generated By columns should be displayed

    // Navigate to module
    await sessionPage.navigateToModule();

    // Verify element visibility
    const isVisible = await sessionPage.verifyElementVisible('session-create-button');
    expect(isVisible).toBe(true);

    await page.waitForLoadState('domcontentloaded');
  });

  test('UTC-1794: Verify Version Number column is populated for each record when multiple versions', async ({ page }) => {
    // Test Case: UTC-1794
    // Summary: Verify Version Number column is populated for each record when multiple versions exist in history
    // Description: Feature: Version Metadata – Version Number Populated Scenario: Verify Version Number column is populated for each record Given multiple versions exist in history When the table loads Then each version row should display a valid version number

    // Navigate to module
    await sessionPage.navigateToModule();

    // Verify page loaded and module accessible
    await sessionPage.waitForSessionTable();
    const tableVisible = await sessionPage.verifyTableData();
    expect(tableVisible).toBe(true);

    await page.waitForLoadState('domcontentloaded');
    expect(page.url()).toContain('dataverse');
  });

  test('UTC-1795: Verify Generated Date & Time is displayed for each version when versions exist w', async ({ page }) => {
    // Test Case: UTC-1795
    // Summary: Verify Generated Date & Time is displayed for each version when versions exist with stored timestamps
    // Description: Feature: Version Metadata – Generated Date & Time Populated Scenario: Verify Generated Date & Time is displayed for each version Given versions exist with stored timestamps When the Version History list loads Then each version row should show Generated Date & Time correctly

    // Navigate to module
    await sessionPage.navigateToModule();

    // Verify element visibility
    const isVisible = await sessionPage.verifyElementVisible('session-create-button');
    expect(isVisible).toBe(true);

    await page.waitForLoadState('domcontentloaded');
  });

  test('UTC-1796: Verify Generated By column shows correct user name when versions were created by', async ({ page }) => {
    // Test Case: UTC-1796
    // Summary: Verify Generated By column shows correct user name when versions were created by different users
    // Description: Feature: Version Metadata – Generated By Populated Scenario: Verify Generated By column shows correct user name Given versions were created by different users When the Version History list loads Then each version row should display the correct Generated By user name

    // Navigate to module
    await sessionPage.navigateToModule();

    // Interact with dropdown
    await sessionPage.selectFromDropdown('session-status', 'active');

    await page.waitForLoadState('domcontentloaded');
    expect(page.url()).toContain('dataverse');
  });

  test('UTC-1797: Verify metadata helps distinguish versions clearly when multiple versions exist ', async ({ page }) => {
    // Test Case: UTC-1797
    // Summary: Verify metadata helps distinguish versions clearly when multiple versions exist (V1, V2, V3)
    // Description: Feature: Version Metadata – Traceability Across Versions Scenario: Verify metadata helps distinguish versions clearly Given multiple versions exist (V1, V2, V3) When the user compares metadata across rows Then each version should be uniquely identifiable using version number + date/time + generated by

    // Navigate to module
    await sessionPage.navigateToModule();

    // Verify page loaded and module accessible
    await sessionPage.waitForSessionTable();
    const tableVisible = await sessionPage.verifyTableData();
    expect(tableVisible).toBe(true);

    await page.waitForLoadState('domcontentloaded');
    expect(page.url()).toContain('dataverse');
  });

  test('UTC-1798: Verify default value shown if metadata is unavailable when a version record exis', async ({ page }) => {
    // Test Case: UTC-1798
    // Summary: Verify default value shown if metadata is unavailable when a version record exists with missing metadata field (ex: Generated By is null)
    // Description: Feature: Version Metadata – Missing Metadata Shows N/A Scenario: Verify default value shown if metadata is unavailable Given a version record exists with missing metadata field (ex: Generated By is null) When the Version History list loads Then the missing metadata field should display “N/A” And UI should not break

    // Navigate to module
    await sessionPage.navigateToModule();

    // Fill input field
    await sessionPage.clickCreateButton();
    await sessionPage.fillInputField('name', 'Test Session');

    const inputVisible = await sessionPage.isInputVisible('session-name');
    expect(inputVisible).toBe(true);
  });

  test('UTC-1799: Verify table renders correctly even if metadata missing for multiple records whe', async ({ page }) => {
    // Test Case: UTC-1799
    // Summary: Verify table renders correctly even if metadata missing for multiple records when multiple version records exist with missing metadata values
    // Description: Feature: Version Metadata – UI Stability With Missing Metadata Scenario: Verify table renders correctly even if metadata missing for multiple records Given multiple version records exist with missing metadata values When the Version History table loads Then the table should render without crash or alignment issues

    // Navigate to module
    await sessionPage.navigateToModule();

    // Verify table/grid
    await sessionPage.waitForSessionTable();
    const count = await sessionPage.getSessionCount();
    expect(count).toBeGreaterThanOrEqual(0);
  });

  test('UTC-1800: Verify metadata loads correctly after refresh/reopen when Version History table ', async ({ page }) => {
    // Test Case: UTC-1800
    // Summary: Verify metadata loads correctly after refresh/reopen when Version History table shows metadata values
    // Description: Feature: Version Metadata – Metadata Binding on Refresh Scenario: Verify metadata loads correctly after refresh/reopen Given Version History table shows metadata values When the user refreshes the page or reopens Version History panel Then the metadata values should load correctly again

    // Navigate to module
    await sessionPage.navigateToModule();

    // Verify table/grid
    await sessionPage.waitForSessionTable();
    const count = await sessionPage.getSessionCount();
    expect(count).toBeGreaterThanOrEqual(0);
  });
  test.afterEach(async ({ page }, testInfo) => {
    if (testInfo.status !== testInfo.expectedStatus) {
      await page.screenshot({
        path: `screenshots/failed-${testInfo.title.replace(/[^a-zA-Z0-9]/g, '-')}-${Date.now()}.png`,
        fullPage: true
      });
    }
  });
});
