import { test, expect } from '../../../fixtures/auth.fixture';
import { SessionPage } from '../../../pages/session.page';
import { TestData } from '../../../test-data/test-data';
import { SessionSelectors, CommonSelectors } from '../../../selectors';

/**
 * Test Suite: Verify metadata fields are displayed in Version History table when version history contains JSON versions
 * URS: URS-DV-DM-17
 * SRS: SRS-131
 * SDS: SDS-131
 */
test.describe('URS-DV-DM-17: Verify metadata fields are displayed in Version History tabl', () => {
  let sessionPage: SessionPage;

  test.beforeEach(async ({ page }) => {
    // Authentication handled by global-setup.ts and storageState
    // Just initialize page object
    sessionPage = new SessionPage(page);

    // Navigate to home page
    await page.goto(TestData.urls.homePage);
    await page.waitForLoadState('load');
  });

  test('UTC-1770: Verify metadata fields are displayed in Version History table when version histo', async ({ page }) => {
    // Test Case: UTC-1770
    // Summary: Verify metadata fields are displayed in Version History table when version history contains JSON versions
    // Description: Feature: Version Metadata – Metadata Columns Visible Scenario: Verify metadata fields are displayed in Version History table Given version history contains JSON versions When the user opens Version History list Then Version Number, Created Date & Time, and Generated User details should be displayed

    // Navigate to module
    await sessionPage.navigateToModule();

    // Verify element visibility
    const isVisible = await sessionPage.verifyElementVisible('session-create-button');
    expect(isVisible).toBe(true);

    await page.waitForLoadState('domcontentloaded');
  });

  test('UTC-1771: Verify displayed version number matches stored value when a version exists in hi', async ({ page }) => {
    // Test Case: UTC-1771
    // Summary: Verify displayed version number matches stored value when a version exists in history with stored version number V5
    // Description: Feature: Version Metadata – Version Number Accuracy Scenario: Verify displayed version number matches stored value Given a version exists in history with stored version number V5 When the Version History list is displayed Then the UI should display version number exactly as stored (V5)

    // Navigate to module
    await sessionPage.navigateToModule();

    // Verify element visibility
    const isVisible = await sessionPage.verifyElementVisible('session-create-button');
    expect(isVisible).toBe(true);

    await page.waitForLoadState('domcontentloaded');
  });

  test('UTC-1772: Verify creation date and time match stored value when a version entry exists wit', async ({ page }) => {
    // Test Case: UTC-1772
    // Summary: Verify creation date and time match stored value when a version entry exists with stored timestamp
    // Description: Feature: Version Metadata – Created Date & Time Accuracy Scenario: Verify creation date and time match stored value Given a version entry exists with stored timestamp When the Version History list is displayed Then the Created Date & Time should match the stored timestamp without alteration

    // Navigate to module
    await sessionPage.navigateToModule();

    // Verify page loaded and module accessible
    await sessionPage.waitForSessionTable();
    const tableVisible = await sessionPage.verifyTableData();
    expect(tableVisible).toBe(true);

    await page.waitForLoadState('domcontentloaded');
    expect(page.url()).toContain('dataverse');
  });

  test('UTC-1773: Verify generated user name/details match stored value when a version was generat', async ({ page }) => {
    // Test Case: UTC-1773
    // Summary: Verify generated user name/details match stored value when a version was generated by User A
    // Description: Feature: Version Metadata – Generated User Accuracy Scenario: Verify generated user name/details match stored value Given a version was generated by User A When the Version History list is displayed Then the Generated User details should display User A correctly as stored

    // Navigate to module
    await sessionPage.navigateToModule();

    // Interact with dropdown
    await sessionPage.selectFromDropdown('session-status', 'active');

    await page.waitForLoadState('domcontentloaded');
    expect(page.url()).toContain('dataverse');
  });

  test('UTC-1774: Verify metadata is displayed without changes or reformatting when stored metadat', async ({ page }) => {
    // Test Case: UTC-1774
    // Summary: Verify metadata is displayed without changes or reformatting when stored metadata contains specific formatting (ex: date format, username format)
    // Description: Feature: Version Metadata – No Format Modification Scenario: Verify metadata is displayed without changes or reformatting Given stored metadata contains specific formatting (ex: date format, username format) When the UI binds metadata to Version History table Then metadata should be displayed exactly as stored without modification

    // Navigate to module
    await sessionPage.navigateToModule();

    // Verify element visibility
    const isVisible = await sessionPage.verifyElementVisible('session-create-button');
    expect(isVisible).toBe(true);

    await page.waitForLoadState('domcontentloaded');
  });

  test('UTC-1775: Verify metadata values remain correct after refresh/relogin when version history', async ({ page }) => {
    // Test Case: UTC-1775
    // Summary: Verify metadata values remain correct after refresh/relogin when version history is displayed with metadata values
    // Description: Feature: Version Metadata – Metadata Persists After Refresh Scenario: Verify metadata values remain correct after refresh/relogin Given version history is displayed with metadata values When the user refreshes the page or logs out and logs in again Then the metadata should remain accurate and unchanged

    // Navigate to module
    await sessionPage.navigateToModule();

    // Verify element visibility
    const isVisible = await sessionPage.verifyElementVisible('session-create-button');
    expect(isVisible).toBe(true);

    await page.waitForLoadState('domcontentloaded');
  });

  test('UTC-1776: Verify metadata helps differentiate versions correctly when multiple versions ex', async ({ page }) => {
    // Test Case: UTC-1776
    // Summary: Verify metadata helps differentiate versions correctly when multiple versions exist with different timestamps and generated users
    // Description: Feature: Version Metadata – Multiple Versions Differentiation Scenario: Verify metadata helps differentiate versions correctly Given multiple versions exist with different timestamps and generated users When the Version History list is displayed Then each version should show correct unique metadata values per record

    // Navigate to module
    await sessionPage.navigateToModule();

    // Interact with dropdown
    await sessionPage.selectFromDropdown('session-status', 'active');

    await page.waitForLoadState('domcontentloaded');
    expect(page.url()).toContain('dataverse');
  });
  test.afterEach(async ({ page }, testInfo) => {
    if (testInfo.status !== testInfo.expectedStatus) {
      await page.screenshot({
        path: `screenshots/failed-${testInfo.title.replace(/[^a-zA-Z0-9]/g, '-')}-${Date.now()}.png`,
        fullPage: true
      });
    }
  });
});
